version: '3.8'

services:
    proxy:
        image: nginx:1.24.0-alpine
        container_name: proxy
        hostname: proxy
        volumes:
            - ./proxy/nginx.build.conf:/etc/nginx/nginx.conf
        command: /bin/sh -c "nginx -g 'daemon off;'"
        ports:
            - "8080:80"
            - "8443:443"
        depends_on:
            - server
            - client
        networks:
            - app
    client:
        container_name: client
        hostname: client
        build:
            context: '.'
            dockerfile: ./client/docker/Dockerfile
            target: build
        volumes:
            - ./client:/app
            - /app/node_modules
        ports:
            - "8004:80"
        depends_on:
            - server
        networks:
            - app
    server:
        container_name: server
        hostname: server
        build:
            context: '.'
            dockerfile: ./server/Dockerfile
            target: build
        volumes:
            - ./server:/app
            - /app/node_modules
        ports:
        - "8002:8002"
        networks:
            - app

networks:
    app:
        driver: bridge